#!/bin/sh 
# mv /tmp/resolv.conf /tmp/resolv.conf.hold 
# echo "nameserver 223.5.5.5" >>  /tmp/resolv.conf1
# echo $foreign_option_1 >> /tmp/resolv.conf1
mv /tmp/resolv.conf.d/resolv.conf.auto /tmp/resolv.conf.auto.hold
echo "#Interface openvpn" > /tmp/resolv.conf.d/resolv.conf.auto
echo $foreign_option_1 | sed -e 's/dhcp-option DOMAIN/domain/g' -e 's/dhcp-option DNS/nameserver/g' >> /tmp/resolv.conf.d/resolv.conf.auto
echo $foreign_option_2 | sed -e 's/dhcp-option DOMAIN/domain/g' -e 's/dhcp-option DNS/nameserver/g' >> /tmp/resolv.conf.d/resolv.conf.auto
echo $foreign_option_3 | sed -e 's/dhcp-option DOMAIN/domain/g' -e 's/dhcp-option DNS/nameserver/g' >> /tmp/resolv.conf.d/resolv.conf.auto
cat /tmp/resolv.conf.auto.hold >> /tmp/resolv.conf.d/resolv.conf.auto

